# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-31 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171229_0011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_support',
            new_name='CustomerSupport',
        ),
    ]
