# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-25 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='live',
        ),
    ]
