# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-17 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20171218_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='auction',
            name='bids',
        ),
        migrations.AlterField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.Seller'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction'),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Bid'),
        ),
        migrations.AddField(
            model_name='auction',
            name='bids',
            field=models.ManyToManyField(through='auctions.AuctionBid', to='auctions.Bid'),
        ),
    ]
