# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-26 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction',
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ManyToManyField(to='auctions.Auction'),
        ),
    ]
