# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-27 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20171226_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
