# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-29 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('Antiques', 'Antiques'), ('Automobiles', 'Automobiles'), ('Computers', 'Computers'), ('Mobiles', 'Mobiles')], default='Mobiles', max_length=64, verbose_name='category'),
        ),
    ]
