# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-31 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20171230_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Credit/Debit Card', 'Credit/Debit Card'), ('Paypal', 'Paypal')], max_length=64, verbose_name='method')),
                ('payed_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.Bid')),
            ],
        ),
    ]
