# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-31 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20171231_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
