# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-31 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20171231_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='replyed',
            field=models.BooleanField(default=False),
        ),
    ]
