# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-31 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_ticket_replyed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
